sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
before_install:
- chmod +x deploy.sh
- npm prune
- npm set progress=false
- npm install -g npm@latest
script: npm run build-prod
env:
  global:

after_success: 
  # ./deploy.sh 
