sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
before_install:
- chmod +x deploy.sh
- npm prune
- npm set progress=false
- npm install -g npm@latest
script: npm run build-prod
env:
  global:
  - secure: lIMC9IPeQOsRP/y1UAsNo7jveBvtdfXWKF/yx1qrpzU+ll7ohlu0gNzUkG78tslzjnCgAuaCGcLciXpnE0j5TcvHwCX1fMIh5ZPsxNO0QAUDYyyGhowW9yvd/VRqETLkv2lXPRb1CaMulMlzAI7Ka0I33d3tWBi5kZvZNkZRtu6i3PhGl0NGHxfIcVS0pd73Zr/5xpmJoA1j2GMu62nbffOb1pmZpWwNSR41mOqDLWRt+nzBEuvqSAahIG1LzUVyx8b9xl8lwrfKhB96JXh+LvQ3ej3relxJAk2+N8zmp1rjVTNM0sboagWvu1t4WnWh35SenI53i6k3IFsiFlsQH+jXdWFyT46W3c12NPC6Bbl2f34J+r45zXf9beNJp80F1STItG/Wvbwy1FyAzVD04E1e31MQWKbyHQkb3v688n1hJyHr47cbBuymEf7G7nwgPaveZQguARW2GhNpjVHCYJWMBsm2zelNddVCMcyvH7RzEgdzgiueqpNzA3qA1c6jqRfILhO5mbEWj0GnqIT1Eiu75flvxLKC0btM5JMN5VXOhpSZN+7MeQnjCO1MC/zCcZLi+KB9Q7OAmbo3CYiOOH7tYM0ZL6I9RMq0jhhzfC/ISP3FgGYcxRpZmDWESMOlmMtTmwT5hFNyygIVMzSLC3S51ZiTVoyeMC9FOSVxeCA=
  - secure: 5viD4Mvxo22XAt1gO5t4NrIzHb5JdMg3V2AXG3I8I3Exi11uef04NJaLlkp3pR/FruFTnuFCg7W4yB87AjLtzwLk2WvrxCLiepuewF6CQ2ktRRPpH4bc2Vw3RDZ4zY20sI+bDjl3Jq2Nk63n6dL6kVeIH9pBwRte5YvzFyBj9Y+E+5CiG8BDZQ++DCwCDaR2GmLMXyyOG3YtjHB8hFEfFIHup102zPoNZY/yC0JTtoj2CaBrCoAxNahcil8LMDsUjQ6w9MYNGJQOBFWCNA+UNdH6Ce03DTtk6dOg5RSPRwkiYG5rub8gv6wcmiHcdlR5F9Wt63ezMmyX2anPTEVTaBP0EJi0ImWWMEUHK8/RQDgJkYR96q3K3YjpZDmBbg5lFlQEOucjzHDgyAxpUhnf8BAE/MlBg6ub2EF8BvFQ7IiuUA47pPEu3fliE7FIXqsFxzx0dSvnwqJ4gRQzmXfe63nV0XTE+SLXUSlEp/+htZqT7mLZ3SLmaZeUZK+MhKI5aXtTm1Q5upiN6tNAJMvyYn0QFRhdWe64RE+sPbkZ9AE5euSx2Jn4pUcOBQUPDcTd2tQkV19s/o1Y7q1Ehm2KuzOH81FOHFfh+Cp0wlq1mwIjRf/TYlkI6Hyy3BkBp3Uhrsabzd+fBX1YNntjC1JRZ8/BFVCZzgDT/QHl8nS9wus=
after_success: 
  ./deploy.sh 
