export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const GET_EDIT_POST = "GET_EDIT_POST";
export const CLEAR_ADDEDIT = "CLEAR_ADDEDIT";
export const CHANGE_DATE = "CHANGE_DATE";

export const TOGGLE_ADDEDIT_FORM = "TOGGLE_ADDEDIT_FORM";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const SHOW_FORM = "SHOW_FORM";

export const CHANGE_WEIGHT = "CHANGE_WEIGHT";
export const CHANGE_COMMENT = "CHANGE_COMMENT";
export const CHANGE_PUSHUPS = "CHANGE_PUSHUPS";

export const UPDATE_FILEVIEW = "UPDATE_FILEVIEW";
