module.exports = {
  REST_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  UPLOAD_ROOT: process.env.REACT_APP_UPLOAD_ROOT,
  INSPIRATION_ENDPOINT: process.env.REACT_APP_INSPIRATION_API_ENDPIONT,
  QUESTION_ENDPIONT: process.env.REACT_APP_QUESTION_API_ENDPIONT,
  TRACKS_ENDPIONT: process.env.REACT_APP_TRACKS_API_ENDPIONT,
  MOVIES_ENDPIONT: process.env.REACT_APP_MOVIES_API_ENDPIONT,
  GOOGLE_CLIENTID: process.env.REACT_APP_GOOGLE_OAUTH_CLIENTID,
  STORAGE_KEY: 'MINIBLOG_TOKEN',
  FULL_DATE_FORMAT: 'yyyy-MM-dd',
  DISPLAY_DATE_FORMAT: 'EEE, yyyy-MM-dd',
  ENVIRONMENT: process.env.NODE_ENV,
};
